# Generated by Django 5.2.1 on 2025-06-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0002_products_delete_product"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Products",
        ),
    ]
