# Generated by Django 5.2.1 on 2025-06-04 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0005_alter_products_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=25)),
                ("last_name", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_no", models.CharField(blank=True, max_length=15, null=True)),
                ("password", models.CharField(max_length=10)),
            ],
        ),
    ]
