# Generated by Django 5.2.1 on 2025-06-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0006_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
