# Generated by Django 5.2.1 on 2025-06-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstApp", "0007_alter_customer_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.CharField(max_length=28),
        ),
    ]
